# Generated by Django 5.0.6 on 2025-10-03 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(choices=[('project', 'Project Collaboration'), ('freelance', 'Freelance Opportunity'), ('internship', 'Internship Inquiry'), ('question', 'General Question'), ('other', 'Other')], max_length=200)),
                ('message', models.TextField()),
                ('newsletter', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('replied', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Project title', max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of title', max_length=250, unique=True)),
                ('description', models.TextField(help_text='Detailed project description')),
                ('short_description', models.CharField(blank=True, help_text='Brief summary for cards', max_length=300)),
                ('category', models.CharField(choices=[('web', 'Web Applications'), ('tools', 'Tools & Utilities'), ('GUI', 'Python GUIs'), ('desktop', 'Desktop Applications'), ('automation', 'Automation Scripts'), ('api', 'API Development'), ('data', 'Data Analysis')], default='web', max_length=20)),
                ('featured', models.BooleanField(default=False, help_text='Mark as featured project')),
                ('github_url', models.URLField(help_text='GitHub repository URL')),
                ('live_url', models.URLField(blank=True, help_text='Live demo/deployment URL', null=True)),
                ('documentation_url', models.URLField(blank=True, help_text='Documentation URL', null=True)),
                ('image', models.ImageField(blank=True, help_text='Project screenshot or logo', null=True, upload_to='projects/')),
                ('thumbnail', models.ImageField(blank=True, help_text='Thumbnail image', null=True, upload_to='projects/thumbnails/')),
                ('technologies', models.TextField(help_text='Comma-separated list of technologies used (e.g., Python, Django, React)')),
                ('status', models.CharField(choices=[('active', 'Active Development'), ('completed', 'Completed'), ('archived', 'Archived'), ('on_hold', 'On Hold')], default='completed', max_length=20)),
                ('start_date', models.DateField(blank=True, help_text='Project start date', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Project completion date', null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('visible', models.BooleanField(default=True, help_text='Show on website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['order', '-featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('language', 'Programming Language'), ('framework', 'Framework'), ('library', 'Library'), ('database', 'Database'), ('tool', 'Tool'), ('platform', 'Platform'), ('service', 'Service')], default='language', max_length=50)),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon class (e.g., fab fa-python)', max_length=100)),
                ('color', models.CharField(blank=True, help_text='Hex color code (e.g., #3776ab)', max_length=7)),
                ('website', models.URLField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Technologies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='website.project')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
